### ISSUE TITLE
Wrong result types for GetArraySpace() and GetArrayMonitoring()

### ISSUE THREAD

**Issue by a-venger** [devans10/pugo#14]
GetArraySpace() and GetArrayMonitoring() returns Array struct which doesn't have information about metrics returned by the calls.

So there are no types for responses about Array space and monitoring.

**Comment by devans10** [comment]
I added the monitor, space, and controller properties to the Array struct.

**Comment by a-venger** [comment]
Why numeral types are not pointers?
